require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DeliveryUnitsController do

  # This should return the minimal set of attributes required to create a valid
  # DeliveryUnit. As you add validations to DeliveryUnit, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all delivery_units as @delivery_units" do
      delivery_unit = DeliveryUnit.create! valid_attributes
      get :index
      assigns(:delivery_units).should eq([delivery_unit])
    end
  end

  describe "GET show" do
    it "assigns the requested delivery_unit as @delivery_unit" do
      delivery_unit = DeliveryUnit.create! valid_attributes
      get :show, :id => delivery_unit.id.to_s
      assigns(:delivery_unit).should eq(delivery_unit)
    end
  end

  describe "GET new" do
    it "assigns a new delivery_unit as @delivery_unit" do
      get :new
      assigns(:delivery_unit).should be_a_new(DeliveryUnit)
    end
  end

  describe "GET edit" do
    it "assigns the requested delivery_unit as @delivery_unit" do
      delivery_unit = DeliveryUnit.create! valid_attributes
      get :edit, :id => delivery_unit.id.to_s
      assigns(:delivery_unit).should eq(delivery_unit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DeliveryUnit" do
        expect {
          post :create, :delivery_unit => valid_attributes
        }.to change(DeliveryUnit, :count).by(1)
      end

      it "assigns a newly created delivery_unit as @delivery_unit" do
        post :create, :delivery_unit => valid_attributes
        assigns(:delivery_unit).should be_a(DeliveryUnit)
        assigns(:delivery_unit).should be_persisted
      end

      it "redirects to the created delivery_unit" do
        post :create, :delivery_unit => valid_attributes
        response.should redirect_to(DeliveryUnit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved delivery_unit as @delivery_unit" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeliveryUnit.any_instance.stub(:save).and_return(false)
        post :create, :delivery_unit => {}
        assigns(:delivery_unit).should be_a_new(DeliveryUnit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeliveryUnit.any_instance.stub(:save).and_return(false)
        post :create, :delivery_unit => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested delivery_unit" do
        delivery_unit = DeliveryUnit.create! valid_attributes
        # Assuming there are no other delivery_units in the database, this
        # specifies that the DeliveryUnit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DeliveryUnit.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => delivery_unit.id, :delivery_unit => {'these' => 'params'}
      end

      it "assigns the requested delivery_unit as @delivery_unit" do
        delivery_unit = DeliveryUnit.create! valid_attributes
        put :update, :id => delivery_unit.id, :delivery_unit => valid_attributes
        assigns(:delivery_unit).should eq(delivery_unit)
      end

      it "redirects to the delivery_unit" do
        delivery_unit = DeliveryUnit.create! valid_attributes
        put :update, :id => delivery_unit.id, :delivery_unit => valid_attributes
        response.should redirect_to(delivery_unit)
      end
    end

    describe "with invalid params" do
      it "assigns the delivery_unit as @delivery_unit" do
        delivery_unit = DeliveryUnit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeliveryUnit.any_instance.stub(:save).and_return(false)
        put :update, :id => delivery_unit.id.to_s, :delivery_unit => {}
        assigns(:delivery_unit).should eq(delivery_unit)
      end

      it "re-renders the 'edit' template" do
        delivery_unit = DeliveryUnit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeliveryUnit.any_instance.stub(:save).and_return(false)
        put :update, :id => delivery_unit.id.to_s, :delivery_unit => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested delivery_unit" do
      delivery_unit = DeliveryUnit.create! valid_attributes
      expect {
        delete :destroy, :id => delivery_unit.id.to_s
      }.to change(DeliveryUnit, :count).by(-1)
    end

    it "redirects to the delivery_units list" do
      delivery_unit = DeliveryUnit.create! valid_attributes
      delete :destroy, :id => delivery_unit.id.to_s
      response.should redirect_to(delivery_units_url)
    end
  end

end
