require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PaymentHistoriesController do

  # This should return the minimal set of attributes required to create a valid
  # PaymentHistory. As you add validations to PaymentHistory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PaymentHistoriesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all payment_histories as @payment_histories" do
      payment_history = PaymentHistory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:payment_histories).should eq([payment_history])
    end
  end

  describe "GET show" do
    it "assigns the requested payment_history as @payment_history" do
      payment_history = PaymentHistory.create! valid_attributes
      get :show, {:id => payment_history.to_param}, valid_session
      assigns(:payment_history).should eq(payment_history)
    end
  end

  describe "GET new" do
    it "assigns a new payment_history as @payment_history" do
      get :new, {}, valid_session
      assigns(:payment_history).should be_a_new(PaymentHistory)
    end
  end

  describe "GET edit" do
    it "assigns the requested payment_history as @payment_history" do
      payment_history = PaymentHistory.create! valid_attributes
      get :edit, {:id => payment_history.to_param}, valid_session
      assigns(:payment_history).should eq(payment_history)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PaymentHistory" do
        expect {
          post :create, {:payment_history => valid_attributes}, valid_session
        }.to change(PaymentHistory, :count).by(1)
      end

      it "assigns a newly created payment_history as @payment_history" do
        post :create, {:payment_history => valid_attributes}, valid_session
        assigns(:payment_history).should be_a(PaymentHistory)
        assigns(:payment_history).should be_persisted
      end

      it "redirects to the created payment_history" do
        post :create, {:payment_history => valid_attributes}, valid_session
        response.should redirect_to(PaymentHistory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved payment_history as @payment_history" do
        # Trigger the behavior that occurs when invalid params are submitted
        PaymentHistory.any_instance.stub(:save).and_return(false)
        post :create, {:payment_history => {}}, valid_session
        assigns(:payment_history).should be_a_new(PaymentHistory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PaymentHistory.any_instance.stub(:save).and_return(false)
        post :create, {:payment_history => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested payment_history" do
        payment_history = PaymentHistory.create! valid_attributes
        # Assuming there are no other payment_histories in the database, this
        # specifies that the PaymentHistory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PaymentHistory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => payment_history.to_param, :payment_history => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested payment_history as @payment_history" do
        payment_history = PaymentHistory.create! valid_attributes
        put :update, {:id => payment_history.to_param, :payment_history => valid_attributes}, valid_session
        assigns(:payment_history).should eq(payment_history)
      end

      it "redirects to the payment_history" do
        payment_history = PaymentHistory.create! valid_attributes
        put :update, {:id => payment_history.to_param, :payment_history => valid_attributes}, valid_session
        response.should redirect_to(payment_history)
      end
    end

    describe "with invalid params" do
      it "assigns the payment_history as @payment_history" do
        payment_history = PaymentHistory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PaymentHistory.any_instance.stub(:save).and_return(false)
        put :update, {:id => payment_history.to_param, :payment_history => {}}, valid_session
        assigns(:payment_history).should eq(payment_history)
      end

      it "re-renders the 'edit' template" do
        payment_history = PaymentHistory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PaymentHistory.any_instance.stub(:save).and_return(false)
        put :update, {:id => payment_history.to_param, :payment_history => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested payment_history" do
      payment_history = PaymentHistory.create! valid_attributes
      expect {
        delete :destroy, {:id => payment_history.to_param}, valid_session
      }.to change(PaymentHistory, :count).by(-1)
    end

    it "redirects to the payment_histories list" do
      payment_history = PaymentHistory.create! valid_attributes
      delete :destroy, {:id => payment_history.to_param}, valid_session
      response.should redirect_to(payment_histories_url)
    end
  end

end
