require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PickupsController do

  # This should return the minimal set of attributes required to create a valid
  # Pickup. As you add validations to Pickup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all pickups as @pickups" do
      pickup = Pickup.create! valid_attributes
      get :index
      assigns(:pickups).should eq([pickup])
    end
  end

  describe "GET show" do
    it "assigns the requested pickup as @pickup" do
      pickup = Pickup.create! valid_attributes
      get :show, :id => pickup.id.to_s
      assigns(:pickup).should eq(pickup)
    end
  end

  describe "GET new" do
    it "assigns a new pickup as @pickup" do
      get :new
      assigns(:pickup).should be_a_new(Pickup)
    end
  end

  describe "GET edit" do
    it "assigns the requested pickup as @pickup" do
      pickup = Pickup.create! valid_attributes
      get :edit, :id => pickup.id.to_s
      assigns(:pickup).should eq(pickup)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pickup" do
        expect {
          post :create, :pickup => valid_attributes
        }.to change(Pickup, :count).by(1)
      end

      it "assigns a newly created pickup as @pickup" do
        post :create, :pickup => valid_attributes
        assigns(:pickup).should be_a(Pickup)
        assigns(:pickup).should be_persisted
      end

      it "redirects to the created pickup" do
        post :create, :pickup => valid_attributes
        response.should redirect_to(Pickup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pickup as @pickup" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pickup.any_instance.stub(:save).and_return(false)
        post :create, :pickup => {}
        assigns(:pickup).should be_a_new(Pickup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pickup.any_instance.stub(:save).and_return(false)
        post :create, :pickup => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pickup" do
        pickup = Pickup.create! valid_attributes
        # Assuming there are no other pickups in the database, this
        # specifies that the Pickup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pickup.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => pickup.id, :pickup => {'these' => 'params'}
      end

      it "assigns the requested pickup as @pickup" do
        pickup = Pickup.create! valid_attributes
        put :update, :id => pickup.id, :pickup => valid_attributes
        assigns(:pickup).should eq(pickup)
      end

      it "redirects to the pickup" do
        pickup = Pickup.create! valid_attributes
        put :update, :id => pickup.id, :pickup => valid_attributes
        response.should redirect_to(pickup)
      end
    end

    describe "with invalid params" do
      it "assigns the pickup as @pickup" do
        pickup = Pickup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pickup.any_instance.stub(:save).and_return(false)
        put :update, :id => pickup.id.to_s, :pickup => {}
        assigns(:pickup).should eq(pickup)
      end

      it "re-renders the 'edit' template" do
        pickup = Pickup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pickup.any_instance.stub(:save).and_return(false)
        put :update, :id => pickup.id.to_s, :pickup => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pickup" do
      pickup = Pickup.create! valid_attributes
      expect {
        delete :destroy, :id => pickup.id.to_s
      }.to change(Pickup, :count).by(-1)
    end

    it "redirects to the pickups list" do
      pickup = Pickup.create! valid_attributes
      delete :destroy, :id => pickup.id.to_s
      response.should redirect_to(pickups_url)
    end
  end

end
